version: '3'

volumes:
  tn_mysql_data: {}

services:
  tn_exercise:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    env_file: .env
    depends_on:
      - tn_mysql
    ports:
      - "8000:8000"

  tn_mysql:
    image: mysql:5.7
    volumes:
      - tn_mysql_data:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "8100:3306"
